OOified trip_manage.php
GibbonEdu/module-tripPlanner pull request #27
Opened 2020-10-14 20:47 UTC by jimbo8098

Per https://github.com/GibbonEdu/core/pull/1124 

Aside from the general OOification, I've:

- Queries run as gateways now
- Now performing some previously in-code checks in SQL instead which should provide some minor benefits when it comes to efficiency.

2020-10-14 21:11 UTC, jimbo8098 commented
Oh, btw, tried setting the namespace to "Gibbon\Module\TripPlanner\Domain" on the gateway but that didn't work out for me. I don't think it's autoloading

2020-10-16 00:55 UTC, SKuipers requested changes
Overall looking good. I've added a couple changes and suggestions. The namespace should work in the format of Gibbon\Module\ModuleName

2020-10-16 00:55 UTC, SKuipers commented on Trip Planner/trips_manage.php
> +use Gibbon\Domain\TripPlanner\TripGateway;
```suggestion
use Gibbon\Module\TripPlanner\Domain;
```

2020-10-16 00:55 UTC, SKuipers commented on Trip Planner/src/Domain/TripPlanner/TripGateway.php
> +namespace Gibbon\Domain\TripPlanner;
```suggestion
namespace Gibbon\Module\TripPlanner\Domain;
```

2020-10-16 00:55 UTC, SKuipers commented on Trip Planner/trips_manage.php
> +include "./modules/Trip Planner/src/Domain/TripPlanner/TripGateway.php";
```suggestion

```

2020-10-16 00:55 UTC, SKuipers commented on Trip Planner/trips_manage.php
> +            if ($eutFilter) {
Some leftover code from testing? 🤔

2020-10-16 00:55 UTC, SKuipers commented on Trip Planner/trips_manage.php
> +        $criteria = $tripGateway->newQueryCriteria()
Add `true` as the parameter here if you'd like to paginate the results.

2020-10-16 00:55 UTC, SKuipers commented on Trip Planner/trips_manage.php
>          }
Hmm, is this leftover from the non-ooified code?

2020-10-17 16:44 UTC, jimbo8098 commented
I assume your assumption on the domain namespace rename and removal on the include is that it's autoloaded but I wasn't able to do that using the namespace format you suggested (with some amendments):

```
Uncaught Exception: League\Container\Exception\NotFoundException - Alias (Gibbon\Module\TripPlanner\Domain\TripGateway) is not being managed by the container
Line 266 in vendor/league/container/src/Container.php
Line 93 in vendor/league/container/src/Container.php
Line 172 in /home/jimspeir/Projects/Trip-Planner/Trip Planner/trips_manage.php
Line 85 in src/View/View.php
Line 365 in src/View/Page.php
Line 658 in index.php
```
This occurs with the include removed as suggested and the newly formatted use statement:

```
include "./modules/Trip Planner/moduleFunctions.php";
#include "./modules/Trip Planner/src/Domain/TripPlanner/TripGateway.php";

use Gibbon\Forms\Form;
use Gibbon\Tables\DataTable;
use Gibbon\Services\Format;
use Gibbon\Module\TripPlanner\Domain\TripGateway;
#use Gibbon\Module\TripPlanner\Domain;
```
This looks like it did load but can't be referenced within $container->get.

When I used the `use Gibbon\Module\TripPlanner\Domain` I received an error saying that TripGateway wasn't managed by the container but I feel that makes sense considering that's just the namespace.

Cleaned up a lot of the code in this PR a lot in the last commit too with breadcrumbs amended to work using the new style, SQL for SchoolYears being better too although I seem to remember using addSelectSchoolYears in past form ooifications. I see those are part of the DatabaseFormFactory class according to the gibbon docs site but it's not accessible on a normal Form. Could be worthwhile looking into that in another commit.

2021-01-13 02:24 UTC, raynichc commented
I thought I'd bump this, as I'm in the process of working on v1.3.00 of the Trip Planner. I'd be happy to merge this into the new branch and make the fixes as necessary if you don't have the time @jimbo8098.

2021-01-13 07:34 UTC, jimbo8098 commented
I'm not sure given the time that's passed but I believe this is ready for merging

2021-01-15 03:09 UTC, merged

2021-01-15 03:09 UTC, raynichc commented
Thanks Jimbo, I've merged it in.

2021-01-18 02:12 UTC, SKuipers commented
Thanks Ray and Jim! My apologies, these PRs seem fall off my radar much easier because they're not part of the core. Thanks for bumping the issue & handling the merge. In glancing back at the code, I think it is functional as-is with the file includes. 

It looks like the issue stemed from the file location not matching the file namespace. In this case, the `Trip Planner/src/Domain/TripPlanner/TripGateway.php` has been nested in an extra `TripPlanner` folder, which doesn't match the `Gibbon\Module\TripPlanner\Domain` namespace (which expects TripGateway.php inside the `Trip Planner/src/Domain` folder).